### ISSUE TITLE
Arduino SAMD boards support? [HAPTICFEEDBACK usage]

### ISSUE THREAD

**Issue by YiepNet** [matzman666/VR-Rifle-Firmware#3]
hi im working on a diy vr gun project and i was wondering if it woud be posible to use a samd board instead of the arduino due due to cost and waste of io i cant afford mucht so yea 25 euros instad of 60 woud be great

**Comment by YiepNet** [comment]
and due to size of the board

**Comment by YiepNet** [comment]
whats the HAPTICFEEDBACK_INPUT_PIN usage for or how is  HAPTICFEEDBACK_OUTPUT_PIN used is it an pwm signal or an high low output?

**Comment by matzman666** [comment]
In theory Arduino SAMD should also work, but I am not sure whether some pins need to be changed. 

As far as I remember  HAPTICFEEDBACK_OUTPUT_PIN uses a PWM signal. But it has now been a long time since I did something with this project.

**Comment by YiepNet** [comment]
thank you for the response.
i will buy some samd chips and make a pcb.
for referens im using a nerf delta burst [ nerf laser gun with haptic feed back wich is discontinued and cant  be used without the app wich is deleted but the hardware is extreamly solid for a child toy ] also i will publishthe files and make them opensource when its working also if its alright with you. i want to link your github and your files in this project.
